mdapipkg/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Valuation__c</fullName>
        <label>Valuation</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

mdapipkg/objects/Building__c.object
<CustomObject>
    <description>Test object for account trigger</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>InitialCost__c</fullName>
        <label>Initial Cost</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/classes/AccountHandler.cls
public class AccountHandler {
    public static void handleAccountUpdate(List<Account> accsList, Map<Id, Account> accsMap) {
        List<Account> changedAccs = new List<Account>();
        for(Account acc : accsList) {
            if(acc.Valuation__c != accsMap.get(acc.Id).Valuation__c) {
                changedAccs.add(acc);
            }
        }
        if(!changedAccs.isEmpty()) {
            recalculateBuildingsCost(changedAccs);
        }
    }
    
    public static void recalculateBuildingsCost(List<Account> accs) {
        Set<Id> accIds = new Map<Id, Account>(accs).keySet();
        List<Building__c> bldgs = new List<Building__c>();
        List<Account> changedAccs = [SELECT Id, Name, Valuation__c, (SELECT Id, Cost__c, InitialCost__c FROM Buildings__r) FROM Account WHERE Id IN :accIds];
        for(Account acc : changedAccs) {
            for(Building__c bldg : acc.Buildings__r) {
                System.debug('!!!!!!!!!');
                bldg.Cost__c = bldg.InitialCost__c * acc.Valuation__c;
                bldgs.add(bldg);
            }
        }
        update bldgs;
	}
        
}