mdapipkg/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Valuation__c</fullName>
        <label>Valuation</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

mdapipkg/objects/Building__c.object
<CustomObject>
    <description>Test object for account trigger</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>InitialCost__c</fullName>
        <label>Initial Cost</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/classes/AccountTriggerTest.cls
@isTest
public class AccountTriggerTest {
	@isTest
    public static void testUpdateAccount() {
        Account acc = new Account(Name='Test Name');
        insert acc;
        Building__c bldg = new Building__c(Name='Test bldg', InitialCost__c=500.00, Height__c=500, Account__c=acc.Id);
        insert bldg;
        System.assertEquals(null, bldg.Cost__c);
        
        acc = [SELECT Id, Valuation__c FROM Account WHERE id = :acc.Id];
        acc.Valuation__c = 4;
        update acc;
        
        bldg = [SELECT Id, Cost__c FROM Building__c WHERE Id = :bldg.Id];
        System.assertEquals(2000.00, bldg.Cost__c);
    }
}