mdapipkg/objects/Building__c.object
<CustomObject>
    <description>Test object for account trigger</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>InitialCost__c</fullName>
        <label>Initial Cost</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapipkg/classes/ContactTriggerTest.cls
@isTest
public class ContactTriggerTest {
	@isTest
    public static void testContactUpdate() {
        Account acc = new Account(Name='Test Name');
        insert acc;
        Building__c bldg = new Building__c(Name='Test bldg', InitialCost__c=500.00, Height__c=500, Account__c=acc.Id);
        insert bldg;
        Contact cont = new Contact(LastName='TestName', AccountId=acc.Id, Building__c=bldg.Id);
        insert cont;
        
        cont.AccountId = null;
        update cont;
        
        cont = [SELECT Id, AccountId, Building__c FROM Contact WHERE Id = :cont.Id];
        System.assertEquals(null, cont.AccountId);
        System.assertEquals(null, cont.Building__c);
    }
}